[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bck-nd-hlpr"
version = "1.0.0"
description = "The Backend Helper - Lightweight Architecture CLI"
readme = "README.md"
authors = [
  { name = "Coxibius", email = "tu_email@example.com" },
]
requires-python = ">=3.9"
dependencies = [
    "typer",
    "colorama",
    "rich",
    "requests",
    "tomli; python_version < '3.11'",
    "pyyaml",
    "textual",
    "tree-sitter",
    "tree-sitter-c-sharp",
    "tree-sitter-javascript",
    "tree-sitter-java",
    "tree-sitter-php"
]

[project.scripts]
bck-nd = "bck_nd_hlpr.cli:app"

[tool.setuptools.packages.find]
where = ["src"]
