[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bck-nd-hlpr"
version = "1.0.4"
description = "The Backend Helper - Lightweight Architecture CLI"
readme = "README.md"
authors = [
  { name = "Coxibius", email = "tu_email@example.com" },
]
license = { text = "MIT" }
keywords = ["mcp", "architecture", "diagrams", "mermaid", "cli", "reverse-engineering", "backend"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
requires-python = ">=3.9"
dependencies = [
    "typer",
    "colorama",
    "rich",
    "requests",
    "tomli; python_version < '3.11'",
    "pyyaml",
    "textual",
    "tree-sitter",
    "tree-sitter-c-sharp",
    "tree-sitter-javascript",
    "tree-sitter-java",
    "tree-sitter-php",
    "mcp",
    "python-dotenv"
]

[project.scripts]
bck-nd = "bck_nd_hlpr.cli:app"
bck-nd-mcp = "bck_nd_hlpr.mcp_server:main"

[project.urls]
Homepage = "https://github.com/Coxibius/bck-nd-helper"
Repository = "https://github.com/Coxibius/bck-nd-helper"
"Bug Tracker" = "https://github.com/Coxibius/bck-nd-helper/issues"

[tool.setuptools.packages.find]
where = ["src"]
