import os
from pathlib import Path

GITHUB_ACTION_YAML = """name: Deploy Documentation to GitHub Pages

# Builds the HTML portal with the packaged `bck-nd` CLI and deploys it to
# GitHub Pages. Triggered on pushes to main (and manually via workflow_dispatch).
# Feature branches are never deployed — preview locally with `bck-nd docs .`.

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install bck-nd-hlpr
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip setuptools wheel
          # This repo IS the tool → install from source (never PyPI cache).
          # Consumer repos generated by `bck-nd init-ci` install from PyPI.
          if [ -f pyproject.toml ] && grep -q 'name = "bck-nd-hlpr"' pyproject.toml; then
            python -m pip install --no-cache-dir .
          else
            python -m pip install --no-cache-dir "bck-nd-hlpr>=2.0.0"
          fi

      - name: Smoke-test CLI entry points
        run: |
          set -euo pipefail
          command -v bck-nd
          bck-nd --help
          bck-nd docs --help
          python -c "from importlib.metadata import version; print('bck-nd-hlpr', version('bck-nd-hlpr'))"

      - name: Generate documentation portal
        run: |
          set -euo pipefail
          rm -rf docs
          mkdir -p docs
          bck-nd docs . --output docs
          touch docs/.nojekyll

      - name: Assert docs artifact
        run: |
          set -euo pipefail
          test -f docs/index.html
          test -s docs/index.html
          echo "docs/index.html size: $(wc -c < docs/index.html) bytes"
          ls -la docs/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
"""


def generate_ci_workflow(root_path: str = "."):
    """
    Generates the GitHub Action workflow file for auto-documentation.
    """
    workflows_dir = Path(root_path) / ".github" / "workflows"
    workflow_file = workflows_dir / "bck-nd-docs.yml"

    workflows_dir.mkdir(parents=True, exist_ok=True)

    with open(workflow_file, "w", encoding="utf-8") as f:
        f.write(GITHUB_ACTION_YAML)

    return workflow_file
