from pathlib import Path
from typing import Optional

from bck_nd_hlpr.core.utils.secure_write import (
    SecureWriteError,
    atomic_write_artifact,
    ensure_existing_artifact_allowed,
    read_verified_artifact,
    validate_artifact_targets,
)


_GITHUB_ACTION_BODY = """name: Deploy Documentation to GitHub Pages

# Builds the HTML portal with the packaged `bck-nd` CLI and deploys it to
# GitHub Pages. Triggered on pushes to main (and manually via workflow_dispatch).
# Feature branches are never deployed - preview locally with `bck-nd docs .`.

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install bck-nd-hlpr
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip setuptools wheel build

          if [ -f pyproject.toml ] && grep -q 'name = "bck-nd-hlpr"' pyproject.toml; then
            # This repo IS the tool. Wipe path-shadow leftovers, build a wheel
            # from src-layout only, then install THAT wheel (never a stale tree).
            rm -rf ./bck_nd_hlpr ./build ./dist ./*.egg-info ./src/*.egg-info
            test -f src/bck_nd_hlpr/cli/mcp_server.py
            test -f src/bck_nd_hlpr/cli/formatters.py
            python -m build --wheel
            python -m pip install --no-cache-dir --force-reinstall dist/bck_nd_hlpr-*.whl
          else
            python -m pip install --no-cache-dir --force-reinstall "bck-nd-hlpr>=2.0.2"
          fi

      - name: Assert installed package paths
        run: |
          set -euo pipefail
          python - <<'PY'
          from importlib.metadata import version, files
          from pathlib import Path

          ver = version("bck-nd-hlpr")
          print(f"installed version: {ver}")

          pkg_files = list(files("bck-nd-hlpr") or [])
          mcp = next(
              p for p in pkg_files
              if str(p).replace("\\", "/").endswith("cli/mcp_server.py")
          )
          mcp_path = Path(mcp.locate())
          text = mcp_path.read_text(encoding="utf-8")

          stale = "from bck_nd_hlpr.core.todo_hunter import scan_for_todos, get_todos_table_string"
          if stale in text:
              raise SystemExit(
                  f"PATH CONFUSION: stale mcp_server at {mcp_path}\n"
                  "get_todos_table_string must come from cli.formatters, not core.todo_hunter"
              )
          if "from bck_nd_hlpr.cli.formatters import" not in text:
              raise SystemExit(f"mcp_server missing formatters import: {mcp_path}")

          # Package must live under site-packages, never the checkout src/ tree
          resolved = str(mcp_path.resolve())
          if "/src/bck_nd_hlpr/" in resolved or "\\src\\bck_nd_hlpr\\" in resolved:
              raise SystemExit(f"PATH CONFUSION: imported checkout tree instead of installed package: {resolved}")

          print(f"mcp_server OK: {mcp_path}")
          PY

      - name: Smoke-test CLI entry points
        run: |
          set -euo pipefail
          command -v bck-nd
          bck-nd --help
          bck-nd docs --help

      - name: Generate documentation portal
        run: |
          set -euo pipefail
          rm -rf docs
          mkdir -p docs
          bck-nd docs . --output docs
          touch docs/.nojekyll

      - name: Assert docs artifact
        run: |
          set -euo pipefail
          test -f docs/index.html
          test -s docs/index.html
          echo "docs/index.html size: $(wc -c < docs/index.html) bytes"
          ls -la docs/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
"""

CI_WORKFLOW_MARKER = "# Generated by bck-nd-hlpr\n"
LEGACY_GITHUB_ACTION_YAML = _GITHUB_ACTION_BODY
GITHUB_ACTION_YAML = CI_WORKFLOW_MARKER + _GITHUB_ACTION_BODY
_REQUIRED_GITIGNORE_RULES = (
    "!.bck-nd/",
    ".bck-nd/cache/",
    "!.bck-nd/requirements/",
    "!.bck-nd/requirements/**",
)


def _is_known_workflow(content: bytes) -> bool:
    if content.startswith(CI_WORKFLOW_MARKER.encode("utf-8")):
        return True
    try:
        normalized = content.decode("utf-8").replace("\r\n", "\n")
    except UnicodeDecodeError:
        return False
    return normalized == LEGACY_GITHUB_ACTION_YAML


def _updated_gitignore(existing: Optional[bytes]) -> Optional[bytes]:
    original = existing or b""
    bom = b"\xef\xbb\xbf" if original.startswith(b"\xef\xbb\xbf") else b""
    payload = original[len(bom):]
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SecureWriteError("Artifact publication was denied safely.") from exc
    current_lines = text.splitlines()
    missing = [rule for rule in _REQUIRED_GITIGNORE_RULES if rule not in current_lines]
    if not missing:
        return None

    newline = "\r\n" if "\r\n" in text else "\n"
    separator = "" if not text or text.endswith(("\n", "\r")) else newline
    block = "# bck-nd generated cache (requirements remain versioned)" + newline
    block += newline.join(missing) + newline
    return bom + (text + separator + block).encode("utf-8")


def generate_ci_workflow(root_path: str = "."):
    """Generate verified CI artifacts without overwriting user-owned files."""
    try:
        root = Path(root_path).resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise SecureWriteError("Artifact publication was denied safely.") from exc
    workflows_dir = root / ".github" / "workflows"
    workflow_file = workflows_dir / "bck-nd-docs.yml"
    gitignore_file = root / ".gitignore"

    # Validate every target and existing ancestor before creating .github or
    # changing either artifact.
    validate_artifact_targets(root, (workflow_file, gitignore_file))
    ensure_existing_artifact_allowed(root, workflow_file, _is_known_workflow)
    gitignore_update = _updated_gitignore(
        read_verified_artifact(root, gitignore_file)
    )

    atomic_write_artifact(
        root,
        workflow_file,
        GITHUB_ACTION_YAML.encode("utf-8"),
        existing_validator=_is_known_workflow,
    )
    if gitignore_update is not None:
        atomic_write_artifact(root, gitignore_file, gitignore_update)

    return workflow_file
